# Generated by Django 5.0.7 on 2024-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_elapsed_time',
            field=models.IntegerField(default=0),
        ),
    ]
