# Generated by Django 5.0.7 on 2024-07-23 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_timerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
