# Generated by Django 5.0.7 on 2024-07-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_rewardlog_useritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardLog',
        ),
    ]
