# Generated by Django 5.0.7 on 2024-07-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_delete_rewardlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='acquired_date',
            new_name='date_awarded',
        ),
    ]
