# Generated by Django 5.0.7 on 2024-07-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_rename_acquired_date_useritem_date_awarded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
